### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by zgrsgr** [cookgreen/Yuris-Revenge#111]
中文字体在部分机型中显示错误，在另一部分机型中显示正常。
可能是系统问题。

**Comment by ShikiSuen** [comment]
@cookgreen May this project use the OTC version of Source Han Sans?
It consists of 4 language versions of Source Han Sans per each weight file but only takes up the hard disk space of 1 language version.

**Comment by cookgreen** [comment]
> @cookgreen May this project use the OTC version of Source Han Sans?
> It consists of 4 language versions of Source Han Sans per each weight file but only takes up the hard disk space of 1 language version.

Sure. His problem caused by ttc format(which may not be supported by his operating system), I will try to find ttf format of this font. If  I failed, I will use OTC version of Source Han Sans :)

**Comment by ShikiSuen** [comment]
@cookgreen OTC is not supported by Windows until certain major update of Windows 10.
Maybe falling back to Droid Sans Fallback or simply use Sarasa Gothic for all purposes:
https://github.com/be5invis/Sarasa-Gothic
(Sarasa Gothic is a customized build of Source Han Sans but all in truetype fonts.)

P.S.: OTC fonts may use TTC file extensions.

**Comment by zgrsgr** [comment]
> @cookgreen在 Windows 10 的某些主要更新（已在几年前发布，当前 Windows 10 版本没有问题）之前，Windows 不支持 OTC。
> 也许回落到Droid Sans回退或简单地使用萨拉萨哥特式的所有目的
> [：https://github.com/be5invis/Sarasa-Gothic（](https://github.com/be5invis/Sarasa-Gothic)
> 萨拉萨哥特式是源汉桑的定制建设，但所有在真实字体。
> 
> P.S.：OTC 字体可能使用 TTC 文件扩展名。



> @cookgreen OTC is not supported by Windows until a certain major update of Windows 10 (already released years ago, not a problem for current Windows 10 releases).
> Maybe falling back to Droid Sans Fallback or simply use Sarasa Gothic for all purposes:
> https://github.com/be5invis/Sarasa-Gothic
> (Sarasa Gothic is a customized build of Source Han Sans but all in truetype fonts.)
> 
> P.S.: OTC fonts may use TTC file extensions.

Sorry,I don’t know about this too much.My system is Windows 10 20H1,It is the newest Windows 10 system,and it isn’t release now.Maybe Microsoft made some changes to something about fonts on this system.

**Comment by cookgreen** [comment]
Oh, then I will use ttf version
ttf is the generic version

**Comment by ShikiSuen** [comment]
@zgrsgr SARASA GOTHIC 是更紗黑體。
@cookgreen Sarasa Gothic is maintained by a Chinese font engineer in Microsoft and is optimized for Windows UI Display.

**Comment by cookgreen** [comment]
@ShikiSuen Ok

**Comment by ShikiSuen** [comment]
@cookgreen I personally disagree the use of wqy font family because it is not optimized for UI font purposes and is comparatively illegible to Sarasa Gothic.

**Comment by cookgreen** [comment]
Well, it can be changed to Sarasa Gothic

**Comment by cookgreen** [comment]
Ok, done
