### ISSUE TITLE
Game crashes when adding Ore Purifier

### ISSUE THREAD

**Issue by amalabey** [cookgreen/Yuris-Revenge#117]
Game crashes with `System.NullReferenceException` when placing Ore Purifier. Am I missing some "mix" files?

**Logs**:
Platform is Windows
Engine version is release-20200202
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL version: 4.6.0 - Build 27.20.100.7988
Using sound device `Headphones (Amals Bose Stereo)`
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80004005
Failed to open device. Falling back to default
Internal mods:
        yr: Red Alert 2 Yuri's Revenge (release-20200202)
        all: All mods (release-20200202)
        cnc: Tiberian Dawn (release-20200202)
        d2k: Dune 2000 (release-20200202)
        modcontent: Mod Content Manager (release-20200202)
        ra: Red Alert (release-20200202)
        ts: Tiberian Sun (release-20200202)
External mods:
        example-{DEV_VERSION}: Example mod ({DEV_VERSION})
        ra2-playtest-20200118: Red Alert 2 (playtest-20200118)
        ratc-release-20200202: Red Alert (Tesla Coil Example) (release-20200202)
        yr-release-20200202: Red Alert 2 Yuri's Revenge (release-20200202)
Loading mod: yr
Failed to initialize hardware cursors. Falling back to software cursors.
Error was: Failed to create hardware cursor `detonate` - Failed to create cursor: CreateIconIndirect(): The parameter is incorrect.

[2020-04-05T17:21:28] Game started
[2020-04-05T17:22:56] Game started
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Traits.Render.WithSpriteBody.<>c__DisplayClass4_0.<.ctor>b__0()
   at OpenRA.Graphics.Animation.Tick()
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.AnimationWrapper.Tick()
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.Tick(Actor self)
   at OpenRA.Mods.Common.Traits.Render.RenderSprites.OpenRA.Traits.ITick.Tick(Actor self)
   at OpenRA.World.<>c.<Tick>b__106_0(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)

----------------------------------------
OpenRA has encountered a fatal error.
  * Log Files are available in Documents\OpenRA\Logs
  * FAQ is available at https://github.com/OpenRA/OpenRA/wiki/FAQ
----------------------------------------
Press any key to continue . . .

**Comment by cookgreen** [comment]
Mine is fine
![](https://user-images.githubusercontent.com/21171007/78627171-6237c780-78c3-11ea-9b49-8f16b308bfe1.JPG)

**Comment by amalabey** [comment]
Probably I am missing some mix file in the contents then. Can you share list of content files you have, so that I can compare with mine?

**Comment by cookgreen** [comment]
Sure

ra2.mix
ra2md.mix
language.mix
langmd.mix

**Comment by amalabey** [comment]
I had copied more *.mix files from the game content and once I removed everything except above, it started working again.

**Comment by cookgreen** [comment]
that's great
