### ISSUE TITLE
Ingame hud text not aligned

### ISSUE THREAD

**Issue by mmtrt** [cookgreen/Yuris-Revenge#124]
![yuri1](https://user-images.githubusercontent.com/2322598/78969795-47628e80-7b21-11ea-8025-ff44afeffbc2.png)

**Comment by cookgreen** [comment]
which branch?

**Comment by cookgreen** [comment]
Works fine in `master` branch
![捕获](https://user-images.githubusercontent.com/21171007/78971039-3e7fb600-7b3d-11ea-8964-8d666a7d142f.JPG)

**Comment by mmtrt** [comment]
using current release yr-playtest-20200408.

**Comment by cookgreen** [comment]
Oh, it has been fixed in `master` branch
