### ISSUE TITLE
Performance issue game lagging

### ISSUE THREAD

**Issue by mmtrt** [cookgreen/Yuris-Revenge#127]
**Version**

`yr-playtest-20200410`

**Issue**

on starting of play game works fine then after as base grows with army game starts to lag heavly on skirmish mode.

**Log files**

[debug.log](https://github.com/cookgreen/Yuris-Revenge/files/4461272/debug.log)
[perf.log](https://github.com/cookgreen/Yuris-Revenge/files/4461275/perf.log)
[server.log](https://github.com/cookgreen/Yuris-Revenge/files/4461277/server.log)
[sound.log](https://github.com/cookgreen/Yuris-Revenge/files/4461278/sound.log)
[traitreport.log](https://github.com/cookgreen/Yuris-Revenge/files/4461279/traitreport.log)

**Comment by alexeik** [comment]
looks like a openra AI can not handle so much units on map.
it takes too much time for it, to make his work done.
or maybe AI does some things that takes so much time .
this logs can not say anymore.
AI is under heave load ->Tick phase takes too much time -> Render phase takes too much time=Lags.
