### ISSUE TITLE
Game no response when play skirmish

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#138]
Map: Powder Keg
Factions:
 Libya
 Random Allies
 Random Soviet
 Random Allies
 France
 Random Allies
 Random Soviet
 Random Yuri
Possbile Reason: Order troopers garrison into the building.

**Comment by zgrsgr** [comment]
> 地图： 火药凯
> 格派系：
> 
> 利比亚随机
> 盟友随机
> 苏联随机
> 盟友
> 法国随机
> 盟友随机
> 苏联随机尤里
> 波斯比勒原因： 命令士兵驻军进入建筑.

Maybe this is the problem of the slave mine?

**Comment by cookgreen** [comment]
> > 地图： 火药凯
> > 格派系：
> > 利比亚随机
> > 盟友随机
> > 苏联随机
> > 盟友
> > 法国随机
> > 盟友随机
> > 苏联随机尤里
> > 波斯比勒原因： 命令士兵驻军进入建筑.
> 
> Maybe this is the problem of the slave mine?

maybe

**Comment by cookgreen** [comment]
@OpenRA
