### ISSUE TITLE
Rocketeers can't attack Flak Cannon

### ISSUE THREAD

**Issue by nr1995** [cookgreen/Yuris-Revenge#141]
I don't know if this was specific to Rocketeers,
but I couldn't attack the soviet Flak Cannon.
It just wouldn't change to a red attack cursor when hovering over it.

Also, as a side note,
where should I send debug logs for random in-game crashes?

**Comment by cookgreen** [comment]
this issue has already been fixed in the repository

**Comment by nr1995** [comment]
> this issue has already been fixed in the repository

Oh, sorry.  I should have checked the closed issues.
