### ISSUE TITLE
MSBuild Problem on Fedora Linux

### ISSUE THREAD

**Issue by meepeek** [cookgreen/Yuris-Revenge#144]
I cloned and try to run make the source in fedora 32 gnome results an error with msbuild command not found error. After I searched the internet, msbuild is a sub command for dotnet. I tried install dotnet but no luck. Please help.

**Comment by cookgreen** [comment]
You can check this:
https://github.com/OpenRA/OpenRA/wiki/Compiling

**Comment by meepeek** [comment]
As the info I searched, it seems fedora 30+ not have a plain msbuild command anymore. It is, instead, dotnet msbuild sub command. Is there a way to config make to use dotnet msbuild instead of msbuild ? I try to modify makefile but it still not work.

**Comment by cookgreen** [comment]
Seem like you can find a way to install msbuild

**Comment by cookgreen** [comment]
@OpenRA Any advice?

**Comment by alexeik** [comment]
@meepeek  you need "mono .net " that will give you msbuild .
so just setup "mono .net" - its a linux version of .net

**Comment by meepeek** [comment]
@alexeik I installed dotnet package already, but in fedora 30+ the command msbuild has changed. It is "dotnet msbuild" instead of "msbuild" so I would like to know if I could config the installation command to replace "msbuild" with "dotnet msbuild"

**Comment by alexeik** [comment]
you installed ".net core", you need ".net mono".

**Comment by meepeek** [comment]
@alexeik I also have mono-devel installed. Here's the result:

thee@localhost  ~  sudo dnf -y install mono-devel
Fedora Modular 32 - x86_64                                  7.3 kB/s | 6.2 kB     00:00    
Fedora Modular 32 - x86_64 - Updates                         13 kB/s | 5.9 kB     00:00    
Fedora 32 - x86_64 - Updates                                8.8 kB/s | 6.3 kB     00:00    
Fedora 32 - x86_64 - Updates                                421 kB/s | 439 kB     00:01    
RPM Fusion for Fedora 32 - Free - Updates                   2.6 kB/s | 3.1 kB     00:01    
RPM Fusion for Fedora 32 - Free - Updates                    11 kB/s | 206 kB     00:18    
RPM Fusion for Fedora 32 - Nonfree - Updates                 15 kB/s |  14 kB     00:00    
RPM Fusion for Fedora 32 - Nonfree - Updates                2.8 kB/s | 9.4 kB     00:03    
Package mono-devel-6.6.0-5.fc32.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 thee@localhost  ~  msbuild
bash: msbuild: command not found
 ✘ thee@localhost  ~  ^C
 ✘ thee@localhost  ~ 

**Comment by alexeik** [comment]
wtf?
https://www.mono-project.com/download/stable/#download-lin-fedora
read this

**Comment by cookgreen** [comment]
@Mono
