### ISSUE TITLE
Health bars at corner of map

### ISSUE THREAD

**Issue by nr1995** [cookgreen/Yuris-Revenge#146]
Got these weird, health-bar-lookin' things in the lower-right corner of my map.
I didn't need to “kill” them to win the match.

![health_bars?](https://i.imgur.com/Aaarq81.png)

**Comment by alexeik** [comment]
Theres are some building or units with wrong XY positions.

**Comment by cookgreen** [comment]
> Theres are some building or units with wrong XY positions.

Which?

**Comment by nr1995** [comment]
> > Theres are some building or units with wrong XY positions.
> 
> Which?

He's saying the health bars are for units or buildings which are just in the wrong place.
But I don't think so.  They're too big for units, and I didn't have to kill them, so not buildings either.

**Comment by alexeik** [comment]
ok
healthbars draws by WORLD
maybe some Building or Unit have offset over Map bounds.

**Comment by cookgreen** [comment]
> ok
> healthbars draws by WORLD
> maybe some Building or Unit have offset over Map bounds.

Maybe

**Comment by cookgreen** [comment]
Which faction do you fight with?

**Comment by nr1995** [comment]
> Which faction do you fight with?

I was using England in the screenshot.

**Comment by cookgreen** [comment]
I mean the oppsite faction

**Comment by nr1995** [comment]
> I mean the opposite faction

Russia.

**Comment by cookgreen** [comment]
> Russia.

That is it, they are maybe planes spawned by boris

**Comment by cookgreen** [comment]
But I use Kill Actor method, so it should not show this error

**Comment by GraionDilach** [comment]
Related to #84 - these units have lost the link via an early reload of planes at Boris before they died and the game silently leaks their state instead of promptly crashing even. I'm not even sure what I did for fixing this (I do remember I started with explicitly crashing when a spawner's state gets leaked first) but I have seen this in RV, elevated this as a blocker before merging and ultimately fixed this months ago when I refactored and merged the spawner code to AS.

**Comment by cookgreen** [comment]
> Related to #84 - these units have lost the link via an early reload of planes at Boris before they died and the game silently leaks their state instead of promptly crashing even. I'm not even sure what I did for fixing this (I do remember I started with explicitly crashing when a spawner's state gets leaked first) but I have seen this in RV, elevated this as a blocker before merging and ultimately fixed this months ago when I refactored and merged the spawner code to AS.

So can you do this once again for YR? because RV's is also from YR.

**Comment by GraionDilach** [comment]
The code necessary to fix this bug (and countless others btw) is publicly available in AS and RV merged it back to their own fork a short time after I pushed it up without my direct involvement. You're free to do the same. This was the point of #37 which you deleted and #84 which you closed. That implies to me you can handle this.

**Comment by cookgreen** [comment]
> The code necessary to fix this bug (and countless others btw) is publicly available in AS and RV merged it back to their own fork a short time after I pushed it up without my direct involvement. You're free to do the same. This was the point of #37 which you deleted and #84 which you closed. That implies to me you can handle this.

Alright, I can handle this.
