### ISSUE TITLE
Edit [Shift] and [Ctrl] Issue

### ISSUE THREAD

**Issue by nr1995** [cookgreen/Yuris-Revenge#151]
We get access to most of the hotkeys in the game,
but there's no option to change the [Shift] key (waypoint mode),
or the [Ctrl] key (force attack mode).
It would be nice to have some customisation there too.

**Comment by cookgreen** [comment]
> MustaphaTR
>> That's an upstream issue, you can't modify the modifier shortcuts (CTRL, ALT, SHIFT).

**Comment by cookgreen** [comment]
https://github.com/OpenRA/OpenRA/issues/15879
