### ISSUE TITLE
Waypoint mode issue

### ISSUE THREAD

**Issue by nr1995** [cookgreen/Yuris-Revenge#152]
While holding [Shift] for waypoint mode,
your unit(s) should not move, even after clicking on open ground.
Currently, they begin moving as soon as you lay down the first position.

Also, it could use a different/clearer line, like vanilla does.

**Comment by cookgreen** [comment]
> MustafaTR
>> That's an OpenRA thing too.

**Comment by cookgreen** [comment]
https://github.com/OpenRA/OpenRA/issues/12408
