### ISSUE TITLE
yuri's revenge files Required

### ISSUE THREAD

**Issue by Ni4ellas** [cookgreen/Yuris-Revenge#176]
I downloaded the red alert 2 and red alert 2 yuri's revenge disk images. after I launch the OpenRA shortcut - Yuri's Revenge on the desktop and write (Yuri's Revenge required) but they are installed.
I transferred from the disks clearly according to the instructions
![Screenshot_3](https://user-images.githubusercontent.com/56962272/140051302-c06cfb33-c61c-4128-be4e-2f8e6f768e99.png)

**Comment by cookgreen** [comment]
which disc do you use?

**Comment by cookgreen** [comment]
@Ni4ellas
