### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kuyin** [cookgreen/Yuris-Revenge#181]
OpenRA engine version release-20200503
Red Alert 2 Yuri's Revenge mod version release-20200503
on map cf45ead2ad40ddd320a40f47e67a0ebb34120739 (Tour of Egypt by Westwood Studios).
Date: 2024-11-28 15:07:22Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Actor world does not have trait of type `OpenRA.Mods.Common.Traits.ResourceRenderer`
   在 OpenRA.TraitDictionary.TraitContainer`1.Get(Actor actor)
   在 OpenRA.Mods.Common.Traits.Harvester.HarvestOrderTargeter.CanTarget(Actor self, Target target, List`1 othersAtTarget, TargetModifiers& modifiers, String& cursor)
   在 OpenRA.Orders.UnitOrderGenerator.OrderForUnit(Actor self, Target target, List`1 actorsAt, CPos xy, MouseInput mi)
   在 OpenRA.Orders.UnitOrderGenerator.<>c__DisplayClass6_0.<GetCursor>b__0(Actor a)
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 OpenRA.Exts.CompareBy[T,U](IEnumerable`1 ts, Func`2 selector, Int32 modifier, Boolean throws)
   在 OpenRA.Orders.UnitOrderGenerator.GetCursor(World world, CPos cell, int2 worldPixel, MouseInput mi)
   在 OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.<>c__DisplayClass17_0.<GetCursor>b__0()
   在 OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   在 OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor(int2 screenPos)
   在 OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   在 OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   在 OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   在 OpenRA.Widgets.Widget.GetCursorOuter(int2 pos)
   在 OpenRA.Game.RenderTick()
   在 OpenRA.Game.Loop()
   在 OpenRA.Game.Run()
   在 OpenRA.Game.InitializeAndRun(String[] args)
   在 OpenRA.Program.Main(String[] args)

**Comment by cookgreen** [comment]
#182
