### ISSUE TITLE
Some units are too bright

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#25]
especially some voxel units

**Comment by GraionDilach** [comment]
How is lack of light adjustments on RenderVoxels an engine problem?

**Comment by cookgreen** [comment]
the voxel color will be checked with the voxel widget

**Comment by GraionDilach** [comment]
That won't lead you anywhere pretty much.

During RA2 development, each vehicle had one low-poly model and one high-poly model. The high-poly model was used for cutscenes and promo material alone while the low-poly variant was only maintained to be used for voxellization. With OpenRA actually emphasizing voxel details and doesn't mishmash them through the limited VPL-based rendering of the legacy game, these low-poly models doesn't withstand the ORA renderer. (The overbrightened "inherited-from-the-RA2-project" RenderVoxels lighting settings doesn't help either).

YR development had no time/effort to develop separate models for voxelization and CGI material, so the high-poly variants were converted instead, resulting with much more details on the artwork itself and explaining the difference between the looks.

**Comment by cookgreen** [comment]
@GraionDilach So you admited that this problem is an Engine problem?

**Comment by GraionDilach** [comment]
Westwood messed up with overdumbing their RA2 artwork. Inferior assets won't produce good looks.

Your best bet is to decrease the ambient lighting on RenderVoxels to hide it somewhat. Considering though taht you already intend to implement additional features over YR (like virus cloud healing Virus), you might want to consider venturing around Project Perfect Mod's Media Hut to use community-made replacement artwork instead.

**Comment by cookgreen** [comment]
> Westwood messed up with overdumbing their RA2 artwork. Inferior assets won't produce good looks.
> 
> Your best bet is to decrease the ambient lighting on RenderVoxels to hide it somewhat. Considering though that you already intend to implement additional features over YR (like virus cloud healing Virus, killdriver and whatnot), you might want to consider venturing around Project Perfect Mod's Media Hut to use community-made replacement artwork instead.

 I can't add too many community-made asset, since this project is a re-implement mod(like RA2) not fan-made mod(like RV)
But I am considering add some new campaigns, maybe a fan-made mod in the futher based on YR.

**Comment by GraionDilach** [comment]
Then your best bet is to tweak the ambient and the diffuse lighting to make it more closer to RA2.
