### ISSUE TITLE
AttachEffect Trait

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#41]
Which can buff/debuff the unit even the defense structure like in MO

**Comment by GraionDilach** [comment]
As the original person who implemented AttachEffect in the very beginning - https://github.com/Ares-Developers/Ares/commit/42fac35ba0ce97d60ab0ad18ebc06afa6b27908c -, I can safely tell you, OpenRA has AttachEffect functionality already.

I'm fully aware though that you're ignoring reasoning.
