### ISSUE TITLE
Identity issue

### ISSUE THREAD

**Issue by GraionDilach** [cookgreen/Yuris-Revenge#50]
The project is named Yuri's Revenge, but it already intends to introduce features YR lacking.

It should probably either get a new name/subname to not misleading people about it not being intended to be an 1:1 conversion.

**Comment by cookgreen** [comment]
The features YR lacking will not appear in the Skrimish mode, even in the mission mode.

If you insist an 1:1 conversion, all the features YR lacking will be removed

**Comment by cookgreen** [comment]
This project will be and must 1:1 conversion

**Comment by cookgreen** [comment]
https://github.com/cookgreen/Yuris-Revenge/commit/7d45765a3b83d4ca2146947595765ac21ba5d582

**Comment by cookgreen** [comment]
If no question, this issue will be closed soon

**Comment by GraionDilach** [comment]
Industrial Plant got the Maintenance ability. I need to look around quite within the yamls.

**Comment by cookgreen** [comment]
Confirmed

**Comment by cookgreen** [comment]
The countdown has been fozened in customized time duration, it will be re-actived at unknown time

**Comment by cookgreen** [comment]
Removed
https://github.com/cookgreen/Yuris-Revenge/commit/64903e1b2947cb6847bea9d5ea1482ece7b71574

**Comment by cookgreen** [comment]
Feel free to find all the features YR lacking, and I will remove them

**Comment by cookgreen** [comment]
If no any other problem, this issue will be closed after 5 countdown

**Comment by GraionDilach** [comment]
I will try to go over the project through the weekend and try to write a report about it.

If I don't get the report by Monday, feel free closing.

**Comment by cookgreen** [comment]
good

**Comment by GraionDilach** [comment]
Cloning Vats/Industrial Plant provides money periodically (weirdly, Ore Purif doesn't).

General polish:
Maintainance's logic is still in (within defaults.yaml), and only the trigger from the IndP was deleted.
CrewKillable trait is everywhere.
Julia's armaments remained.

I don't think I have other concerns regarding the current content.

**Comment by cookgreen** [comment]
https://github.com/cookgreen/Yuris-Revenge/commit/64903e1b2947cb6847bea9d5ea1482ece7b71574

**Comment by cookgreen** [comment]
If no any other problem, this issue will be closed after 3 countdown

**Comment by GraionDilach** [comment]
I think you're done here.
