### ISSUE TITLE
RemoteControlMaster/Slave traits unneeded.

### ISSUE THREAD

**Issue by GraionDilach** [cookgreen/Yuris-Revenge#52]
You can replace the setup with a conditional `ProvidesPrerequsite` upon the RCC only enabled when there is power and then use `GrantConditionOnPrerequsite` on the Robot Tank to disable it when necessary.

**Comment by cookgreen** [comment]
Fixed
https://github.com/cookgreen/Yuris-Revenge/commit/e2dfdc072f053acdea3ebf446b2380fc3f343d42
