### ISSUE TITLE
CameraPitch is wrong.

### ISSUE THREAD

**Issue by GraionDilach** [cookgreen/Yuris-Revenge#56]
All BodyOrientation traits should have the value 85 for CameraPitch,

See https://github.com/OpenRA/OpenRA/issues/16688

**Comment by GraionDilach** [comment]
You forgot the Tech Outpost.

https://github.com/cookgreen/Yuris-Revenge/blob/master/mods/yr/rules/tech-structures.yaml#L138

**Comment by cookgreen** [comment]
done
