### ISSUE TITLE
Out of sync in frame 303

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#65]
OpenRA engine version release-20190314
Red Alert 2 Yuri's Revenge mod version release-20190314
on map dae048e6ccd220fb3958660f425474b5efc04e2e (Tour of Egypt by Westwood Studios).
Date: 2019-09-01 00:26:15Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type System.InvalidOperationException: Out of sync in frame 3037.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in c:\Users\ACCOUNT\Desktop\Yuris-Revenge-master\engine\OpenRA.Game\Network\OrderManager.cs:line 61

**Comment by Mailaender** [comment]
> Compare syncreport.log with other players.

**Comment by cookgreen** [comment]
@Mailaender Yes

**Comment by cookgreen** [comment]
Updated
