### ISSUE TITLE
AI do not build refinerys

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#73]

**Comment by cookgreen** [comment]
You need to set the cash > 20000

**Comment by yaaaaa** [comment]
Why?

**Comment by cookgreen** [comment]
> Why?

Well, current AI seems too `strong`, it will build many buildings at the begining, such as two or three power plants, I still debug the AI

**Comment by yaaaaa** [comment]
Thanks for the answer

**Comment by yaaaaa** [comment]
I find the essence of the problem - both the player and Ai can build structures in two streams at the same time. one in the building itself when you click on it, and the second in the buildings panel

**Comment by cookgreen** [comment]
@OpenRA

**Comment by GraionDilach** [comment]
> both the player and Ai can build structures in two streams at the same time. one in the building itself when you click on it, and the second in the buildings panel

This is an obvious modder error in YAML if this is true, because no other project has this.

**Comment by cookgreen** [comment]
> > both the player and Ai can build structures in two streams at the same time. one in the building itself when you click on it, and the second in the buildings panel
> 
> This is an obvious modder error in YAML if this is true, because no other project has this.

Can you help detect the problem, becuase I check many times and found nothing.
