### ISSUE TITLE
Brige repair hut not working

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#78]

**Comment by cookgreen** [comment]
Which map do you play? I tested the Official Tournament Map 04, it works fine.

**Comment by yaaaaa** [comment]
i tested it in "el dorado" map

**Comment by yaaaaa** [comment]
"Fight" map is have not working hut too

**Comment by yaaaaa** [comment]
"Gold Rush" too

**Comment by MustaphaTR** [comment]
High Bridges are not repairable or destructible.

**Comment by yaaaaa** [comment]
This is issue for Engine or for this mod?

**Comment by MustaphaTR** [comment]
Engine, current High Bridge logic is not much different from the Tunnel Logic.

**Comment by yaaaaa** [comment]
Get it, thanks

**Comment by yaaaaa** [comment]
fixed in current engine bleed.

**Comment by cookgreen** [comment]
Really? which commit?

**Comment by yaaaaa** [comment]
https://github.com/OpenRA/OpenRA/issues/17031

**Comment by cookgreen** [comment]
Updated
