### ISSUE TITLE
Unit overlay du not have build-valid-newurban seqence

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#79]

**Comment by cookgreen** [comment]
which unit?

**Comment by yaaaaa** [comment]
unit name is overlay

**Comment by cookgreen** [comment]
okay

**Comment by cookgreen** [comment]
@yaaaaa Hi, have you tried the new commit? Some people tried the new commit and meet error, do you meet the error when you try the new commit

**Comment by yaaaaa** [comment]
Sorry, but i cant try write now, i just dont try never before to do commits, and this may take a time to learn.

String №52  "	build-valid-newurban:" in the file /sequenses/misk.yaml is skiped.
