### ISSUE TITLE
PNG format sequenses cintax test

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#81]
I see Your mod have support PNG resources... How can i use/test Unit sequenses in PNG format to test it?
Example PNG:
![изображение](https://user-images.githubusercontent.com/11130958/64505236-fa9da780-d2f4-11e9-9056-fe75c25469ca.png)

Any example of sintax seqenses code in yaml?
Chrome.yaml has 

> sell-button-allies: chrome.png
	background: 706,15,43,34
sell-button-allies-hover: chrome.png
	background: 706,49,43,34
sell-button-allies-pressed: chrome.png
	background: 706,83,43,34
sell-button-allies-highlighted: chrome.png
	background: 706,117,43,34
sell-button-allies-highlighted-hover: chrome.png
	background: 706,151,43,34
sell-button-allies-highlighted-pressed: chrome.png
	background: 706,185,43,34
sell-button-allies-disabled: chrome.png
	background: 706,219,43,34
sell-button-allies-highlighted-disabled: chrome.png
	background: 706,219,43,34

Maybe i must write start and end position same way to every frame of PNG file?

**Comment by cookgreen** [comment]
Yes

**Comment by yaaaaa** [comment]
unitname:
	idle: sequence.png
		frame1: 1, 1, 192, 160
		frame2: 1, 161, 192, 160
		frame3: 1, 321, 192, 160
		frame4: 1, 481, 192, 160
		frame5: 1, 641, 192, 160
		frame6: 1, 801, 192, 160

Not work:

Exception of type `System.InvalidOperationException`: Unit `unitname` does not have a sequence named `idle`

**Comment by yaaaaa** [comment]
Maybe I need to public  frame1-6 somewhere?

**Comment by cookgreen** [comment]
Should be:
```
 unitname: sequence.png  
 	idle: 1, 1, 192, 160  
	[other]: x, y, width, height  
```

**Comment by yaaaaa** [comment]
Same Exception... does not have a sequence named idle

And this is way give same Exception too:
```
unitname: 
 	Defaults: sequence.png
		AddExtension: false
	idle: 1, 1, 192, 160  
```

**Comment by cookgreen** [comment]
you can show the log file

**Comment by yaaaaa** [comment]
OpenRA engine version release-20190314
Red Alert 2 Yuri's Revenge mod version playtest-20190825
on map f90a83db5fbafe7c67dbb0b35ccc7a9eaf489e65 (El Dorado by Westwood Studios).
Date: 2019-09-09 08:02:27Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `hive` does not have a sequence named `idle`
   в OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Graphics\SequenceProvider.cs:строка 78
   в OpenRA.Graphics.Animation.GetSequence(String sequenceName) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Graphics\Animation.cs:строка 217
   в OpenRA.Graphics.Animation.PlaySequence(String sequenceName) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Graphics\Animation.cs:строка 98
   в OpenRA.Graphics.Animation.PlayRepeating(String sequenceName) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Graphics\Animation.cs:строка 106
   в OpenRA.Mods.Common.Traits.Render.WithSpriteBody..ctor(ActorInitializer init, WithSpriteBodyInfo info, Func`1 baseFacing) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteBody.cs:строка 76
   в OpenRA.Mods.Common.Traits.Render.WithSpriteBody..ctor(ActorInitializer init, WithSpriteBodyInfo info) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteBody.cs:строка 56
   в OpenRA.Mods.Common.Traits.Render.WithSpriteBodyInfo.Create(ActorInitializer init) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteBody.cs:строка 36
   в OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Actor.cs:строка 106
   в OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 270
   в OpenRA.World.CreateActor(String name, TypeDictionary initDict) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 265
   в OpenRA.Mods.Common.Traits.SpawnMPUnits.SpawnUnitsForPlayer(World w, Player p, CPos sp) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\World\SpawnMPUnits.cs:строка 88
   в OpenRA.Mods.Common.Traits.SpawnMPUnits.WorldLoaded(World world, WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Traits\World\SpawnMPUnits.cs:строка 71
   в OpenRA.World.LoadComplete(WorldRenderer wr) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\World.cs:строка 244
   в OpenRA.Game.StartGame(String mapUID, WorldType type) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 176
   в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\UnitOrders.cs:строка 118
   в OpenRA.Network.OrderManager.TickImmediate() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Network\OrderManager.cs:строка 133
   в OpenRA.Sync.<>c__DisplayClass5.<RunUnsynced>b__4() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 174
   в OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Sync.cs:строка 166
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 591
   в OpenRA.Game.LogicTick() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 640
   в OpenRA.Game.Loop() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 770
   в OpenRA.Game.Run() в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 810
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Game.cs:строка 256
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Game\Support\Program.cs:строка 37

**Comment by cookgreen** [comment]
And I think PNG format only was supported by chrome, Sequence usually use the SHP loader

If you want OpenRA to load a PNG format, should write a new PNG Sequence loader

**Comment by yaaaaa** [comment]
Hmm... ingame asset browser must show png files? maybe game is not load it at all from bits folder?

**Comment by cookgreen** [comment]
Yes, need a PNG Sequence loader

**Comment by yaaaaa** [comment]
It is very hard to write it without deep programming skills?

**Comment by cookgreen** [comment]
@yaaaaa I found a spriteloader called `PngSheet` loader, it can load the png file as Sprite

You can try this:
```
 unitname: sequence
 	idle: 1, 1, 192, 160  
	[other frame]: x, y, width, height  
```

Put the `sequence` into `bits` folder

**Comment by yaaaaa** [comment]
https://github.com/OpenRA/OpenRA/pull/16885/commits/c1e307240425b3053755a360659daa00f384a799

**Comment by yaaaaa** [comment]
it is not merged yet...

**Comment by yaaaaa** [comment]
https://github.com/OpenRA/OpenRA/pull/16885

**Comment by cookgreen** [comment]
https://github.com/OpenRA/OpenRA/blob/dad21fe8792cc5d50115ff9f41094cfbe34ced9d/OpenRA.Mods.Common/SpriteLoaders/PngSheetLoader.cs

**Comment by cookgreen** [comment]
And you can go to `engine\OpenRA.Mods.Common\SpriteLoaders`, you can see a file named `PngSheetLoader.cs`

**Comment by cookgreen** [comment]
We need a png loader which can parse such like  `idle: x, y, width, height`, current png sheet sprite loader only can load a whole png file.
And the current `ISpriteLoader` was called when engine try to load a whole sprite file not a region from a exist file.
@abcdefg30 @pchote

**Comment by yaaaaa** [comment]
Yes, i finded the loader already, but exaple to use for seqenses is not find...

**Comment by cookgreen** [comment]
> Yes, i finded the loader already, but exaple to use for seqenses is not find...

It needs Engine to update, current engine seems don't support such feature...........................

**Comment by yaaaaa** [comment]
> 
> 
> We need a png loader which can parse such like `idle: x, y, width, height`, current png sheet sprite loader only can load a whole png file.
> And the current `ISpriteLoader` was called when engine try to load a whole sprite file not a region from a existed file.
> @abcdefg30 @pchote

Maybe something like easyer?:
`unitname:
	Defaults: unitname.png
		AddExtension: false
	idle: unitname.png
		Frames: 1,2,3,4,5,6
		FrameLength: 32 pix
		FrameLength: 32 pix`

**Comment by cookgreen** [comment]
> > We need a png loader which can parse such like `idle: x, y, width, height`, current png sheet sprite loader only can load a whole png file.
> > And the current `ISpriteLoader` was called when engine try to load a whole sprite file not a region from a existed file.
> > @abcdefg30 @pchote
> 
> Maybe something like easyer?:
> `unitname: Defaults: unitname.png AddExtension: false idle: unitname.png Frames: 1,2,3,4,5,6 FrameLength: 32 pix FrameLength: 32 pix`

Yes

**Comment by cookgreen** [comment]
Need muti-sequence format support, so that we can write a custom sprite sequence format to handle this kind of files
https://github.com/OpenRA/OpenRA/issues/17069

**Comment by GraionDilach** [comment]
Upstream has a metadatad 8bpp-PNG loader already and the Utility has tools how to add the required metadata. This was mostly written with KKND but every other mod is capable to use that.

Look at KKND for examples.

**Comment by yaaaaa** [comment]
Thanks! it's realy work!
