### ISSUE TITLE
Soldiers is die inside the occuping building, then it destroed

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#83]

**Comment by cookgreen** [comment]
Can you describe it more clear?

**Comment by yaaaaa** [comment]
Infantry units is not escape from occupyng building in last one second before its destroed (like in action films or like in RA2/YR)

**Comment by yaaaaa** [comment]
=) Do You stay on MODDB? May I send PM there to You?

**Comment by cookgreen** [comment]
Yeah

yaaaaa <notifications@github.com> 于2019年9月11日周三 上午10:24写道：
