### ISSUE TITLE
Youri Prime cant mindcontrol units

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/Yuris-Revenge#88]

**Comment by cookgreen** [comment]
Which unit can't it control?

**Comment by yaaaaa** [comment]
Any vehicle

**Comment by cookgreen** [comment]
![screenshot](https://user-images.githubusercontent.com/21171007/64906095-46e15100-d714-11e9-904c-d2615b51b336.png)

**Comment by cookgreen** [comment]
It can control

**Comment by yaaaaa** [comment]
soory, this hapend only on third-paty map
