### ISSUE TITLE
Game content not found

### ISSUE THREAD

**Issue by Baytars** [cookgreen/Yuris-Revenge#97]
I have followed the "Install the content" instructions to put mix files into ~/.openra/Content/yr/ and ~/.openra/Content/ra2/ but when I run launch-game.sh the game window just prompted me to install game content from CD. Must I install from CD? Can I just put the mix file in place accordingly?
The note says "Normally installing the content from the ingame content installer is enough." But there's only one option in content installer - Advanced install, and it requires disc ... Any other option?

OS: Manjaro Linux

**Comment by cookgreen** [comment]
That is because your OpenRA content folder has changed
OpenRA will change default content folder in some situation
I will add utility command which can show the current OpenRA content folder

**Comment by Baytars** [comment]
> That is because your OpenRA content folder has changed
> OpenRA will change default content folder in some situation
> I will add utility command which can show the current OpenRA content folder

As I anticipated. Thanks for your reply. Hopefully the utility comes out soon. By the way, should the command be simple, can you paste here for preview?

**Comment by cookgreen** [comment]
> > That is because your OpenRA content folder has changed
> > OpenRA will change default content folder in some situation
> > I will add utility command which can show the current OpenRA content folder
> 
> As I anticipated. Thanks for your reply. Hopefully the utility comes out soon. By the way, should the command be simple, can you paste here for preview?

Run `Utility.cmd` and type `--display-content-path`

**Comment by Baytars** [comment]
> > > That is because your OpenRA content folder has changed
> > > OpenRA will change default content folder in some situation
> > > I will add utility command which can show the current OpenRA content folder
> > 
> > 
> > As I anticipated. Thanks for your reply. Hopefully the utility comes out soon. By the way, should the command be simple, can you paste here for preview?
> 
> Run `Utility.cmd` and type `--display-content-path`

Did the trick. Thank you!
